### ISSUE TITLE
Empty strings cause csv-row-to-* procedures to error

### ISSUE THREAD

**Issue by qiemem** [NetLogo/CSV-Extension#1]
For example `show csv:csv-row-to-strings ""` gives:

```
error (NoSuchElementException)
 while observer running SHOW
  called by Command Center

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.util.NoSuchElementException: No more CSV records available
 at org.apache.commons.csv.CSVParser$1.next(CSVParser.java:424)
 at org.apache.commons.csv.CSVParser$1.next(CSVParser.java:390)
 at scala.collection.JavaConversions$JIteratorWrapper.next(JavaConversions.scala:575)
 at scala.collection.Iterator$$anon$19.next(Iterator.scala:401)
 at org.nlogo.extensions.csv.CSVExtension$$anonfun$rowParser$1.apply(CSVExtension.scala:51)
 at org.nlogo.extensions.csv.CSVExtension$$anonfun$rowParser$1.apply(CSVExtension.scala:51)
 at org.nlogo.extensions.csv.CSVExtension$ParserPrimitive.report(CSVExtension.scala:32)
 at org.nlogo.extensions.csv.CSVExtension$ParserPrimitive.report(CSVExtension.scala:29)
 at org.nlogo.prim._externreport.report(_externreport.java:50)
 at org.nlogo.prim.etc._show.perform(_show.scala:13)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.2-RC3
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-462-11M4609)
operating system: Mac OS X 10.9.5 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Analysis

09:01:09.757 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:01:09.757 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:01:09.757 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:01:09.757 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:01:09.757 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:01:09.757 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:01:09.757 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:01:09.757 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:01:09.757 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
09:01:09.757 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
```

**Comment by mrerrormessage** [comment]
What's the expected behavior here? Should this be a LogoException that can be caught by `carefully`? Should it return an empty list?

**Comment by qiemem** [comment]
I'm thinking empty list... Or maybe [""]... Thoughts?

**Comment by arthurhjorth** [comment]
I think that once you have imported a csv, it makes more intuitive sense to check if a string is empty than to check if it exists (or even worse: to have to check the length of the returned list), so I would prefer [" "].

**Comment by qiemem** [comment]
Ya, I'm think `[""]`. `"a"` -> `["a"]`, so `""` -> `[""]`.

Remember, this is for single rows, not for whole files. `csv:csv-to-*` (which does a string of multiple csv rows) should do `""` -> `[]`, since an empty string would mean no rows.

**Comment by arthurhjorth** [comment]
Yeah, I think those two make the most sense to me.

On Thu, Feb 5, 2015 at 11:51 AM, Bryan Head notifications@github.com
wrote:

> Ya, I'm think [""]. "a" -> ["a"], so "" -> [""].
> 
> Remember, this is for single rows, not for whole files. csv:csv-to-*
> (which does a string of multiple csv rows) should do "" -> [], since an
> empty string would mean no rows.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NetLogo/CSV-Extension/issues/1#issuecomment-73092528.

## 

## 

Arthur Hjorth
PhD Student, Learning Sciences
Center for Connected Learning http://ccl.northwestern.edu/
Northwestern University

e: arthur.hjorth@u.northwestern.edu
s: arthurhjorth
m: +1 (773) 943-0013

**Comment by mrerrormessage** [comment]
`[""]` makes sense to me as well. If the reader is at the end of the file, I would favor doing something else, since it seems like you're setting up a situation ripe for infinite loops if it keeps returning `[""]`.

**Comment by qiemem** [comment]
This doesn't affects `csv:file-to*`.

For NetLogo's IO, that's what `file-at-end?` is for. Also, I believe `file-read-line` barfs gracefully after file end.

**Comment by mrerrormessage** [comment]
Sounds good to me then!
