### ISSUE TITLE
Tests fail when running from main NetLogo repository

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/CSV-Extension#5]
```
[info] - csv::from-file *** FAILED ***
[info]   org.nlogo.nvm.EngineException: Extension exception: Couldn't find file: test/simple.csv
[info]   at java.io.FileInputStream.open(Native Method)
[info]   at java.io.FileInputStream.<init>(FileInputStream.java:120)
[info]   at java.io.FileReader.<init>(FileReader.java:55)
[info]   at org.nlogo.extensions.csv.CSVExtension$FileParserPrimitive.report(CSVExtension.scala:45)
[info]   at org.nlogo.prim._externreport.report(_externreport.java:50)
[info]   at org.nlogo.prim._asm_procedureevaluator_report_0.perform()
[info]   at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
[info]   at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
[info]   at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
[info]   at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
[info]   ...
```

@qiemem, would it be OK to modify paths like you did in https://github.com/NetLogo/NW-Extension/commit/d0b42e68ff1ae56be73bb928f987bbed3d53c501 ?

**Comment by qiemem** [comment]
Yes, should be. Though I'm quite confused about why this wasn't caught at the 5.2 release. @frankduncan?

**Comment by frankduncan** [comment]
Oh, it did.  I just made sure the tests passed internal to the repository, and that the failure was not indicative of a bug.

**Comment by qiemem** [comment]
Ah I see. In the future, let me know. I definitely want to know if tests aren't passing in the main repo!
